apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: dns-tuning-acm
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=A custom OpenShift tuning parameters for DNS
      include=openshift-control-plane
      [sysctl]
      net.core.netdev_budget=1000
      net.core.netdev_max_backlog=2000
      net.core.rmem_default=1048576
      net.core.rmem_max=1048576
    name: openshift-dns
  recommend:
  - match:
    - label: "node-role.kubernetes.io/worker"
    priority: 10
    profile: openshift-dns
