apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-dns
  namespace: default
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.PT Protective Technology
    policy.open-cluster-management.io/controls: PR.PT-3 Least Functionality
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-pod-nginx-pod
      spec:
        remediationAction: inform
        severity: low
        namespaceSelector:
          exclude:
            - kube-*
          include:
            - default
        object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: tuned.openshift.io/v1
              kind: Tuned
              metadata:
                name: dns-tuning-acm
                labels:
                  app: dns-tuned
              spec:
                profile:
                  - data: |
                      [main]
                      summary=A custom OpenShift tuning parameters for DNS
                      include=openshift-control-plane
                      [sysctl]
                      net.core.netdev_budget=1000
                      net.core.netdev_max_backlog=2000
                      net.core.rmem_default=1048576
                      net.core.rmem_max=1048576
                    name: openshift-dns
                recommend:
                  - match:
                      - label: node-role.kubernetes.io/worker
                    priority: 10
                    profile: openshift-dns
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-dns
  namespace: default
placementRef:
  name: placement-policy-dns
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-dns
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-dns
  namespace: default
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: cloud, operator: In, values: ["Amazon"]}
