apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  org: RHTE
commonAnnotations:
  note: Hello, I am Ankara cluster!
bases:
- ../../base
patchesStrategicMerge:
- configmap.yaml
- deployment.yaml
