apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: web-app-cluster1
  namespace: web-app
  labels:
    deployment: hello
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: application-portability/lab-5-assets/overlays/cluster1
spec:
  channel:  web-app/web-app-channel
  placement: 
    placementRef: 
      kind: PlacementRule
      name: cluster1
